Chinese:
    SignIn-GUI-Settings:
        GUI-Name: '&c签到菜单 &b&l>>> &8{date}'
        Specified-Month-GUI-Name: '&3&l历史月份 &8{month}月'
        Specified-Year-GUI-Name: '&3&l历史月份 &8{month}月, {year}年'
        Date-Format: 'yyyy年MM月dd日'
        Key:
            Already-SignIn:
                Item: STAINED_CLAY
                Data: 5
                Display-Name: '&a日期 &6{day}号 &a已签到'
                Lore: 
                - ''
                - '&f您已连续签到 &e{continuous} 天&f，继续坚持！'
                - ''
                - '&e点击查看 &d{date} &e的排行榜'
                Close-GUI: true
                Commands:
                - 'litesignin leaderboard {dateText}'
            Comming-Soon:
                Item: STAINED_CLAY
                Data: 9
                Display-Name: '&7日期 &6{day}号 &7未到达'
                Lore: []
            Nothing-SignIn:
                Item: STAINED_CLAY
                Data: 4
                Hide-Enchants: true
                Enchantment:
                - DURABILITY:10
                Display-Name: '&e日期 &6{day}号 &e未签到'
                Lore:
                - ''
                - '&7今天您还没有签到！'
                - ''
                - '&e点击签到'
            Missed-SignIn:
                Item: STAINED_CLAY
                Data: 14
                Display-Name: '&7日期 &6{day}号 &7漏签'
                Lore:
                - ''
                - '&7您可以使用&a补签卡&7进行补签'
                - '&7您拥有的补签卡数量: &6{cards}'
                - ''
                - '&e点击补签'
            Slots:
            - 9
            - 10
            - 11
            - 12
            - 13
            - 14
            - 15
            - 16
            - 17
            - 18
            - 19
            - 20
            - 21
            - 22
            - 23
            - 24
            - 25
            - 26
            - 27
            - 28
            - 29
            - 30
            - 31
            - 32
            - 33
            - 34
            - 35
            - 36
            - 37
            - 38
            - 39
        Others:
            'About':
                Item: WATCH
                Display-Name: '&6关于'
                Close-GUI: false
                Lore:
                - ''
                - '&f您已连续签到 &e{continuous} &f天'
                - '&f当前累计签到次数 &e{total-number} &f次'
                Slot: 49
            'OpenMainMenu':
                Item: BOOK
                Display-Name: '&6返回主菜单'
                Close-GUI: false
                Commands:
                - 'menu'
                Lore:
                - ''
                - '&e点击返回'
                Slot: 45
            'CloseGUI':
                Item: STAINED_GLASS_PANE
                Data: 14
                Display-Name: '&6关闭签到界面'
                Close-GUI: true
                Messages:
                - '{prefix}&c已关闭签到界面。'
                Slot: 53
            'PreviousPage':
                Item: PAPER
                Display-Name: '&d上一页'
                Lore:
                - ''
                - '&7您也可以使用命令 &a/signin gui [月份] [年份]'
                - '&7以切换指定月份与年份的签到菜单查看历史记录'
                - ''
                - '&e点击打开 &b{previousPageYear}年{previousPageMonth}月 &e的签到菜单'
                Slot: 48
                Commands:
                - 'signin gui {previousPageMonth} {previousPageYear}'
            'NextPage':
                Item: PAPER
                Display-Name: '&d下一页'
                Lore:
                - ''
                - '&7您也可以使用命令 &a/signin gui [月份] [年份]'
                - '&7以切换指定月份与年份的签到菜单查看历史记录'
                - ''
                - '&e点击打开 &b{nextPageYear}年{nextPageMonth}月 &e的签到菜单'
                Slot: 50
                Commands:
                - 'signin gui {nextPageMonth} {nextPageYear}'
            'Barrier':
                Item: STAINED_GLASS_PANE
                Data: 7
                Display-Name: '&8分割线'
                Close-GUI: false
                Lore: []
                Slots:
                - 0
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 46
                - 47
                - 51
                - 52
English:
    SignIn-GUI-Settings:
        GUI-Name: '&cSignIn Menu &b&l>>> &8{date}'
        Specified-Month-GUI-Name: '&3&lHistorical month &8{month}'
        Specified-Year-GUI-Name: '&3&lHistorical month &8{month}, {year}'
        Date-Format: 'yyyy/MM/dd'
        Key:
            Already-SignIn:
                Item: STAINED_CLAY
                Data: 5
                Display-Name: '&6{day}th &aAlready signed in'
                Lore: 
                - ''
                - '&fYou have been signed in for &e{continuous} consecutive days&f! '
                - '&fPlease keep it up!'
                - ''
                - '&eClick to view &d{date}''s &eleaderboard'
                Close-GUI: true
                Commands:
                - 'litesignin leaderboard {dateText}'
            Comming-Soon:
                Item: STAINED_CLAY
                Data: 9
                Display-Name: '&6{day}th &7Coming soon.'
                Lore: []
            Nothing-SignIn:
                Item: STAINED_CLAY
                Data: 4
                Hide-Enchants: true
                Enchantment:
                - DURABILITY:10
                Display-Name: '&6{day}th &eToday!'
                Lore:
                - ''
                - '&7You haven''t signed in today!'
                - ''
                - '&eRight click to sign-in!'
            Missed-SignIn:
                Item: STAINED_CLAY
                Data: 14
                Display-Name: '&7Absent on &6{day}th'
                Lore: 
                - ''
                - '&7You can use the &aRetrospective card &7to sign-in.'
                - '&7Number of cards you have: &6{cards}'
                - ''
                - '&eRight click to sign-in with retrospective card!'
            Slots:
            - 9
            - 10
            - 11
            - 12
            - 13
            - 14
            - 15
            - 16
            - 17
            - 18
            - 19
            - 20
            - 21
            - 22
            - 23
            - 24
            - 25
            - 26
            - 27
            - 28
            - 29
            - 30
            - 31
            - 32
            - 33
            - 34
            - 35
            - 36
            - 37
            - 38
            - 39
        Others:
            'About':
                Item: WATCH
                Display-Name: '&6About more...'
                Close-GUI: false
                Lore:
                - ''
                - '&fyou have signed in for &e{continuous} &fconsecutive days'
                - '&fCurrent cumulative check in times: &e{total-number}'
                Slot: 49
            'OpenMainMenu':
                Item: BOOK
                Display-Name: '&6Back to main menu.'
                Close-GUI: false
                Commands:
                - 'menu'
                Lore:
                - ''
                - '&eRight click to back.'
                Slot: 45
            'CloseGUI':
                Item: STAINED_GLASS_PANE
                Data: 14
                Display-Name: '&6Close this menu'
                Close-GUI: true
                Messages:
                - '{prefix}&cClose successfully.'
                Slot: 53
            'PreviousPage':
                Item: PAPER
                Display-Name: '&dPrevious Page'
                Lore:
                - ''
                - '&7You can use the command: &a/signin gui [Month] [Year]'
                - '&7to switch the sign-in menu to specify the month and year.'
                - ''
                - '&eClick to open &b{previousPageYear}/{previousPageMonth}''s &eSign-in menu.'
                Slot: 48
                Commands:
                - 'signin gui {previousPageMonth} {previousPageYear}'
            'NextPage':
                Item: PAPER
                Display-Name: '&dNext Page'
                Lore:
                - ''
                - '&7You can use the command: &a/signin gui [Month] [Year]'
                - '&7to switch the sign-in menu to specify the month and year.'
                - ''
                - '&eClick to open &b{previousPageYear}/{previousPageMonth}''s &eSign-in menu.'
                Slot: 50
                Commands:
                - 'signin gui {nextPageMonth} {nextPageYear}'
            'Barrier':
                Item: STAINED_GLASS_PANE
                Data: 7
                Display-Name: ''
                Close-GUI: false
                Lore: []
                Slots:
                - 0
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 46
                - 47
                - 51
                - 52