Reward-Settings:
    #Groups Priority, From top to bottom.
    Groups-Priority:
    - VIP
    - Default
    Permission-Groups:
        #This is the default group, you can't delete it!
        Default:
            #Triggered when sign-in in normally
            Normal-Time:
                #Send messages when signing.
                #Support PlaceholderAPI
                Messages: 
                - '{prefix}&aReceive the sign in reward successfully.'
                #Reward items at check-in
                #In this option, you can directly fill in the name of the original item,
                #or the item in RewardSettings.yml (including manually set, added by command).
                #Format: "[Item name|Collection name]:[Amount]"
                #For example: "diamond:5" Reward 5 diamonds.
                #You can use placeholder "[Minimum value]_[Maximum value]" to randomly reward the number of items.
                #For example: "diamond:1-3" Randomly reward 1-3 diamonds.
                Reward-Items:
                - 'diamond:1'
                - 'gold_ingot:3'
                - 'iron_ingot:6'
                #Send broadcast messages when signing in.
                #The information in this option will be seen by everyone.
                Broadcast-Messages: []
                #Play sounds when signing in.
                #Format: [Sound]-[Volume]-[Pitch]-[Everyone can hear?]
                Play-Sounds: 
                - 'ORB_PICKUP-1-1-FALSE'
                #Execute command when signing in.
                #Format: "[Command type]:[command]"
                #"Command type" can be "op" 、 "server"、 None
                #Corresponding to "player execute command with OP permission", "execute console command", "player execute command normally".
                #For example:
                # "server:say hello" - Execute console command: "say hello"
                # "op:gamemode creative" - Player execute command with OP permission: "gamemode creative"
                # "spawn" - Player execute "spawn" command normally.
                #Support PlaceholderAPI
                Commands: []
            #Triggered when retrospective sign-in.
            Retroactive-Times:
                #Used to prohibit players from obtaining the rewards of the following modules through retrospective sign-in.
                Disabled-Modules:
                    #It is recommended to enable it to prevent players from directly receiving special rewards on certain special dates.
                    Special-Dates: true
                    Special-Weeks: true
                    Special-Times: false
                    Statistics-Times: false
                Play-Sounds: 
                - 'ORB_PICKUP-1-1-FALSE'
                Reward-Items:
                - 'diamond:1'
                - 'gold_ingot:3'
                - 'iron_ingot:6'
            #Triggered when sign-in in for a certain number of consecutive times
            Special-Times:
                3:
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&aYou signed in three days in a row, The reward has &edoubled&a.'
                    Broadcast-Messages:
                    - '{prefix}&aPlayer &e{player} &a signed in for three consecutive days!'
                    Play-Sounds: 
                    - 'LEVELUP-1-0-TRUE'
                    Reward-Items:
                    - 'diamond:1'
                    - 'gold_ingot:3'
                    - 'iron_ingot:6'
                7:
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&aYou signed in for a week in a row, Get extra rewards: &e&lSuper Diamond Sword &aand &eGolden Apple x1'
                    Broadcast-Messages:
                    - '{prefix}&aPlayer &e{player} &a signed in for a week!'
                    Play-Sounds: 
                    - 'LEVELUP-1-0-TRUE'
                    Reward-Items:
                    - 'Super_Diamond_Sword:1'
                    - 'golden_apple:1'
            #Triggered when sign-in in on a speical week.
            Special-Weeks:
                #Sunday
                7:
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&aToday is Sunday, reward an extra golden apple!'
                    Reward-Items:
                    - 'golden_apple:1'
            #Triggered when the sign-in total reaches a certain number of times.
            Statistics-Times:
                100:
                    Messages: 
                    - '{prefix}&aYou signed in for 100 days in a row and got 10K coins reward.'
                    Commands:
                    - 'server:eco give {player} 10000'
            #Triggered when signing in on a special date.
            Special-Dates:
                #Format: Month-Day (Be careful not to correspond to "1-1" on January 1, it should be "01-01")
                '12-25':
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&aToday is Christmas. Happy Christmas!'
                    Reward-Items:
                    - 'apple:64'
            #Triggered when signing in at a special time periods.
            Special-Time-periods:
                #Format: Hour:Minute:Second
                #Minimum: 00:00:00 , Maximum: 23:59:59
                #The absence of minutes or seconds means that the minutes or seconds can be any period of time.
                #Example: '12:00' is '12:00:00-12:00:59' period.
                #         '12' is '12:00:00-12:59:59' period.
                #Ten thirty at night
                '22:30:00':
                    #Option type： On_Time, After_This_Time, Before_This_Time
                    #Corresponding to: sign in on time, sign in after this time, sign in before this time.
                    Option: After_This_Time #Sign in after 22:30:00
                    #Time limit. If Type is not On_Time, you can set a threshold.
                    #"23:59:59" Will be triggered every day from 22:30:00 to 23:59:59.
                    Time-Limit: '23:59:59'
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&aThe server gives you milk, please rest early.'
                    Reward-Items:
                    - 'milk_bucket:1'
                #Three o'clock in the morning
                '03:00:00':
                    Option: Before_This_Time #Sign in before 03:00:00
                    #Triggered between 03:00:00 and 00:00:00.
                    Time-Limit: '00:00:00'
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&aThe server gives you milk, please rest early.'
                    Reward-Items:
                    - 'milk_bucket:1'
            #Triggered when get a new sign-in ranking.
            Special-Ranking:
                #When the player is the first to sign in
                '1':
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&aToday you are the first to sign in, and your reward has doubled!'
                    Reward-Items:
                    - 'diamond:2'
                    - 'gold_ingot:6'
                    - 'iron_ingot:12'
        #Custom group, for example
        VIP:
            #Group permission.
            #When the player has this permission, the parameters of this group will be used.
            #The premise is that you have not mistaken the priority between groups!
            Permission: signin.reward.vip
            Normal-Time:
                Messages: 
                - '{prefix}&aReceive the sign in reward successfully.'
                Reward-Items:
                - 'diamond:3'
                - 'gold_ingot:9'
                - 'iron_ingot:12'
                Commands: 
                - 'server:points give {player} 10'
            Retroactive-Time:
                Disabled-Modules:
                    Special-Dates: true
                    Special-Weeks: true
                    Special-Times: false
                    Statistics-Times: false
                Reward-Items:
                - 'diamond:2'
                - 'gold_ingot:6'
                - 'iron_ingot:12'
            Special-Times:
                3:
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&aYou signed in three days in a row, The reward has &edoubled&a.'
                    Reward-Items:
                    - 'diamond:6'
                    - 'gold_ingot:18'
                    - 'iron_ingot:24'
                    Commands: 
                    - 'server:points give {player} 20'
                7:
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&aYou signed in for a week in a row, Get extra rewards: &e&lSuper Diamond Sword &aand &eGolden Apple x1'
                    Reward-Items:
                    - 'Super_Diamond_Sword:1'
                    - 'golden_apple:1'
            Statistics-Times:
                100:
                    Messages: 
                    - '{prefix}&aYou signed in for 100 days in a row and got 10K coins reward.'
                    Commands:
                    - 'server:eco give {player} 10000'
            Special-Dates:
                '12-25':
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&aToday is Christmas. Happy Christmas!'
                    Reward-Items:
                    - 'apple:64'