#報酬設定
Reward-Settings:
    #優先順位、上から下への順序
    Groups-Priority:
    - VIP
    - Default
    #権限グループの設定
    Permission-Groups:
        #デフォルトのグループです。削除できません。
        Default:
            #通常の状態
            Normal-Time:
                #サインインするときに、プレーヤーにメッセージを送信します
                #PlaceholderAPIをサポートする
                Messages: 
                - '{prefix}&aサインインが完了し、報酬が発行されました。'
                #賞品リスト
                #このオプションでは、元のアイテムの名を入力でと、
                #またはRewardSettings.yml内部のアイテムの名を入力でいます
                #書式： "[アイテムの名|コレクションの名]:[量]"
                #例： "diamond:5" -> 5個のダイヤモンドに報酬を与える
                #"[最小数]-[最大数]"を使用すると、アイテムの数にランダムに報酬を与えることができます。
                #例： "diamond:1-3" -> ランダムに1〜3個のダイヤモンドに報酬を与えます。
                Reward-Items:
                - 'diamond:1'
                - 'gold_ingot:3'
                - 'iron_ingot:6'
                #システムアナウンス情報
                #これは誰もが見ることができるニュースです。
                Broadcast-Messages: []
                #音を出す
                #書式： [音声の名]-[音量]-[トーン]-[誰もがそれを聞くことができるかどうか]
                Play-Sounds:
                - 'ORB_PICKUP-1-1-FALSE'
                #コマンドの実行
                #書式： "[実行タイプ]:[コマンド]"
                #"実行タイプ"は、"op"、"server"、または無にすることができます
                #それぞれ、「プレイヤーがOP権限でコマンドを実行する」、「コンソールコマンドを実行する」、「コマンドを正常に実行する」に対応します。
                #例： 
                # "server:say hello" -> コンソールで"say hello"コマンドを実行します
                # "op:gamemode creative" -> プレイヤーはOP権限で"gamemode creative"コマンドを実行します
                # "spawn" -> コマンド"spawn"は通常どおり実行します
                #PlaceholderAPIをサポートする
                Commands: []
            #トレーサビリティカードの時
            Retroactive-Time:
                #禁止されているモジュール
                Disabled-Modules:
                    Special-Dates: true
                    Special-Weeks: true
                    Special-Times: false
                    Statistics-Times: false
                Reward-Items:
                - 'diamond:1'
                - 'gold_ingot:3'
                - 'iron_ingot:6'
                Play-Sounds:
                - 'ORB_PICKUP-1-1-FALSE'
            #特別な時間
            Special-Times:
                #3回
                3:
                    #デフォルトの報酬を上書きする
                    Override-default-rewards: true
                    Messages: 
                    - '{prefix}&a3日連続でサインインしました！ 報酬が&e2倍&aになりました！'
                    Broadcast-Messages:
                    - '{prefix}&aプレーヤー&e{player}&aが3日連続でサインインしました！'
                    Play-Sounds:
                    - 'LEVELUP-1-0-TRUE'
                    Reward-Items:
                    - 'diamond:1'
                    - 'gold_ingot:3'
                    - 'iron_ingot:6'
                #7回
                7:
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a一週連続でサインインしました！これは追加の報酬です。'
                    Broadcast-Messages:
                    - '{prefix}&aプレーヤー&e{player}&aが一週連続でサインインしました！'
                    Play-Sounds:
                    - 'LEVELUP-1-0-TRUE'
                    Reward-Items:
                    - 'Super_Diamond_Sword:1'
                    - 'golden_apple:1'
            #特別な曜日
            Special-Weeks:
                #日曜日
                7:
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a今は日曜日、これは追加の報酬です。'
                    Reward-Items:
                    - 'golden_apple:1'
            #サインインの総数が一定数に達したときに得られる報酬
            Statistics-Times:
                100:
                    Messages: 
                    - '{prefix}&aサインインの総数は100回に達し、&e10000&aゲームコインを獲得します。'
                    Commands:
                    - 'server:eco give {player} 10000'
            #特別な日
            Special-Dates:
                #書式: MM-dd （月-日）注意！ 1月1日は「1-1」ではなく「01-01」と書いてください。
                '12-25':
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a今日はクリスマス、メリークリスマスです！'
                    Reward-Items:
                    - 'apple:64'
            #毎日の特別な期間
            Special-Time-periods:
                #書式：時：分：秒、左から右へ
                #最小: 00:00:00 、 最大: 23:59:59
                #分または秒を入力しない場合は、任意の期間の意味です
                #例: '12:00' は '12:00:00-12:00:59' の意味です
                #    '12' は '12:00:00-12:59:59' の意味です
                '22:30:00':
                    #オプション： On_Time, After_This_Time, Before_This_Time
                    #その意味では： 現在の時刻、 この後、 この前
                    Option: After_This_Time #22:30:00以後にサインインする
                    #制限時間
                    #"23:59:59" て記入しての意味は、每日22:30:00 〜 23:59:59です。
                    Time-Limit: '23:59:59'
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a夜遅く、休憩に気をつけて！'
                    Reward-Items:
                    - 'milk_bucket:1'
                '03:00:00':
                    Option: Before_This_Time #03:00:00より前
                    Time-Limit: '00:00:00' #00:00:00 〜 03:00:00
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&a夜遅く、休憩に気をつけて！'
                    Reward-Items:
                    - 'milk_bucket:1'
            #毎日の特別なランキング
            Special-Ranking:
                #第一位
                '1':
                    Override-default-rewards: false
                    Messages: 
                    - '{prefix}&aあなたは今日、第一位のサインインしてのプレーヤーです。 報酬を2倍に！'
                    Reward-Items:
                    - 'diamond:1'
                    - 'gold_ingot:3'
                    - 'iron_ingot:6'
        #カスタムグループ、のために使用される
        VIP:
            #権限
            #"Groups-Priority"オプションで優先度を設定します
            Permission: signin.reward.vip
            Normal-Time:
                Messages: 
                - '{prefix}&aサインインが完了し、報酬が発行されました。'
                Reward-Items:
                - 'diamond:3'
                - 'gold_ingot:9'
                - 'iron_ingot:12'
                Commands:
                - 'server:points give {player} 10'
            Retroactive-Time:
                Disabled-Modules:
                    Special-Dates: true
                    Special-Weeks: true
                    Special-Times: false
                    Statistics-Times: false
                Reward-Items:
                - 'diamond:2'
                - 'gold_ingot:6'
                - 'iron_ingot:12'
            Special-Times:
                3:
                    Override-default-rewards: true
                    Messages:
                    - '{prefix}&a3日連続でサインインしました！ 報酬が&e2倍&aになりました！'
                    Reward-Items:
                    - 'diamond:6'
                    - 'gold_ingot:18'
                    - 'iron_ingot:24'
                    Commands:
                    - 'server:points give {player} 20'
                7:
                    Override-default-rewards: false
                    Messages:
                    - '{prefix}&a一週連続でサインインしました！これは追加の報酬です。'
                    Reward-Items:
                    - 'Super_Diamond_Sword:1'
                    - 'golden_apple:1'
            Statistics-Times:
                100:
                    Messages:
                    - '{prefix}&aサインインの総数は100回に達し、&e10000&aゲームコインを獲得します。'
                    Commands:
                    - 'server:eco give {player} 10000'
            Special-Dates:
                '12-25':
                    Override-default-rewards: false
                    Messages:
                    - '{prefix}&a今日はクリスマス、メリークリスマスです！'
                    Reward-Items:
                    - 'apple:64'